// <auto-generated />
using AvanceradLabb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvanceradLabb3.Migrations
{
    [DbContext(typeof(InterestContext))]
    [Migration("20250424084659_withLinks")]
    partial class withLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvanceradLabb3.Models.Hyperlink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InterestId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonInterestInterestId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonInterestPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonInterestPersonId", "PersonInterestInterestId");

                    b.ToTable("Hyperlinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Scryfall",
                            Url = "http://www.scryfall.com"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Biltema",
                            Url = "http://www.biltema.com"
                        });
                });

            modelBuilder.Entity("AvanceradLabb3.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A collectible card game, and its rewarding and strategic gameplay, compelling characters, and fantastic Multiverse have entertained and delighted fans for more than 30 years. With more than 50 million fans to date, MAGIC is a worldwide phenomenon published in more than 150 countries.",
                            Title = "Magic The Gathering"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Skruva och ha sig lite",
                            Title = "Mecka"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Slåss pang bom krasch!!",
                            Title = "Slåss"
                        });
                });

            modelBuilder.Entity("AvanceradLabb3.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 42,
                            Email = "vd@swedbonk.se",
                            FirstName = "Gustav",
                            LastName = "Eriksson"
                        },
                        new
                        {
                            Id = 2,
                            Age = 72,
                            Email = "mackans@bygghemma.se",
                            FirstName = "McGyver",
                            LastName = "Jonsson"
                        },
                        new
                        {
                            Id = 3,
                            Age = 63,
                            Email = "jean-claude.vandamme@swipnet.se",
                            FirstName = "Jean Claude",
                            LastName = "Van Damme"
                        });
                });

            modelBuilder.Entity("AvanceradLabb3.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PersonInterest");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            InterestId = 3
                        },
                        new
                        {
                            PersonId = 3,
                            InterestId = 3
                        });
                });

            modelBuilder.Entity("AvanceradLabb3.Models.Hyperlink", b =>
                {
                    b.HasOne("AvanceradLabb3.Models.Interest", "Interest")
                        .WithMany("Links")
                        .HasForeignKey("InterestId");

                    b.HasOne("AvanceradLabb3.Models.Person", "Person")
                        .WithMany("Links")
                        .HasForeignKey("PersonId");

                    b.HasOne("AvanceradLabb3.Models.PersonInterest", null)
                        .WithMany("Links")
                        .HasForeignKey("PersonInterestPersonId", "PersonInterestInterestId");

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AvanceradLabb3.Models.PersonInterest", b =>
                {
                    b.HasOne("AvanceradLabb3.Models.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvanceradLabb3.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvanceradLabb3.Models.Interest", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("AvanceradLabb3.Models.Person", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("AvanceradLabb3.Models.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
